source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HXSDK-iOS-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HXSDK-iOS-Example
  pod 'HXSDK'

  target 'HXSDK-iOS-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXSDK-iOS-ExampleUITests' do
    # Pods for testing
  end

end
