source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def ad
  pod 'HXSDK', :path => '../'
  pod 'HXSDK/UBiX', :path => '../'
  pod 'HXSDK/IconAd', :path => '../'
end

target 'HXSDK-iOS-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HXSDK-iOS-Example
  ad
end

target 'HXSDK-OC-Example' do
  use_frameworks!
  
  # Pods for HXSDK-OC-Example
  ad
  pod 'Bugly', '~> 2.6.1'
end
