source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def ad
  pod 'HXSDK', :path => '../'
  pod 'HXSDK/UBiX', :path => '../'
  pod 'HXSDK/IconAd', :path => '../'
end

target 'HXSDK-iOS-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Pods for HXSDK-iOS-Example
  ad

  target 'HXSDK-iOS-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXSDK-iOS-ExampleUITests' do
    # Pods for testing
  end

end

target 'HXSDK-OC-Example' do
  use_frameworks!
  
  # Pods for HXSDK-OC-Example
  ad
end
